version: "3"
services:
  http:
    image: nginx:1.10.3
    volumes:
      - ./www:/usr/src/www
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:web.monprojet.local'
      - 'traefik.docker.network=proxy-traefik_default'
    networks:
      - traefik
      - default
  php:
    image: php:7.3.4-fpm
    volumes:
      - ./www:/usr/src/www
  mysql:
    image: mariadb:10.1.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mon_super_mot_de_passe
      redis:
    image: redis:4
    ports:
      - 6379:6379
networks:
  traefik:
    external:
      name: proxy-traefik_default