version: '3'
services:
  mariadb:
    build: requirements/mariadb
    env_file: .env
    image: mariadb
    container_name: e_mariadb
    restart: unless-stopped
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - docker-network
  wordpress:
    build: requirements/wordpress
    env_file: .env
    image: wordpress
    container_name: e_wordpress
    restart: unless-stopped
    volumes:
        - 'wordpress:/var/www/wordpress/'
    networks:
        - docker-network
    depends_on:
        - mariadb
  nginx:
    build: requirements/nginx
    env_file: .env
    image: nginx
    container_name: e_nginx
    restart: unless-stopped
    volumes:
        - wordpress:/var/www/wordpress/
    networks:
        - docker-network
    ports:
      - 443:443
    depends_on:
        - wordpress



networks:
  docker-network:
    driver: bridge
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/esaci/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/esaci/data/wordpress
      o: bind
