version: '3'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    network_mode: "service:mariadb"
    restart: always
    depends_on:
      - wordpress
  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    command: php -S 0.0.0.0:9000 -t /wordpress/wordpress
    network_mode: "service:mariadb"
    restart: always
    container_name: wordpress
  mariadb:
    hostname: esaci.42.fr
    domainname: esaci.42.fr
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb
    restart: always
    ports:
      - 443:443
      - 80:80
    networks: 
      docker-network:
        aliases:
            - esaci.42.fr

networks:
  docker-network:
    driver: bridge
volumes:
  html:
  db: