version: '3'
services:
  nginx:
    build: requirements/nginx
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
    hostname: esaci.42.fr
    domainname: esaci.42.fr
    ports:
      - 443:443
    volumes:
      - 'wordpress:/var/www/esaci/html/'
    networks: 
      docker-network:
        aliases:
            - esaci.42.fr
  wordpress:
    build: requirements/wordpress
    depends_on:
      - mariadb
    command: php -S 0.0.0.0:9000 -t /wordpress
    restart: always
    volumes:
      - 'wordpress:/var/www/esaci/html/wordpress/'
    container_name: wordpress
    networks:
      - docker-network
  mariadb:
    build: requirements/mariadb
    env_file: .env
    container_name: mariadb
    restart: always
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  db:
    external: false
  wordpress:
    external: false