version: '3'
services:
  mariadb:
    env_file:
    - .env
    networks:
      - docker-network
    build: requirements/mariadb
    image: mariadb
    container_name: e_mariadb
    restart: unless-stopped
    volumes:
      - 'db:/var/lib/mysql'
  wordpress:
    env_file:
    - .env
    networks:
      - docker-network
    build: requirements/wordpress
    image: wordpress
    container_name: e_wordpress
    restart: unless-stopped
    volumes:
        - 'wordpress:/var/www/wordpress/'
    depends_on:
        - mariadb
  nginx:
    env_file:
    - .env
    networks:
      - docker-network
    build: requirements/nginx
    image: nginx
    container_name: e_nginx
    restart: unless-stopped
    volumes:
        - wordpress:/var/www/wordpress/
    ports:
      - 443:443
    depends_on:
        - wordpress


networks:
  docker-network:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/esaci/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/esaci/data/wordpress
      o: bind
