version: "3"
services:
  mariadb:
    image: mariadb
    container_name: e_mysql
    ports:
      - "3306:80"
    volumes:
      - "/home/esaci/data/mariadb/:/var/lib/mysql"
    build:
      context: ./requirements/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always
    networks:
          esacicorp:
            aliases:
              - mysql
  wordpress:
    image: wordpress
    container_name: e_wordpress
    ports:
      - "9000:80"
    volumes:
      - "/home/esaci/data/html:/var/www/html"
    build:
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always
    networks:
          esacicorp:
            aliases:
              - wordpress
  nginx:
    image: nginx
    container_name: e_nginx
    ports:
      - "80:80"
    volumes:
      - /home/esaci/data/html:/var/www/html
      -  /home/esaci/data/nginx:/etc/nginx/conf.d
    build:
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    restart: always
    networks:
        esacicorp:
          aliases:
            - nginx
networks:
     esacicorp:
