version: "3"
services:
  nginx:
    image: e_nginx:latest
    container_name: e_nginx
    restart: always
    network_mode: "bridge"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .